insert into public.programs(title, description, tags, free, indoor, outdoor, organizer, location_name)
values
('iHuman Youth Society – Arts Drop-In',
 'Creative drop-in for youth with arts, music, and mentorship.',
 '{arts,drop-in,community,indoor,free}', true, true, false, 'iHuman Youth Society', 'iHuman Studio'),
('Boyle Street – Youth Drop-In',
 'Youth-friendly daytime drop-in with support workers and snacks.',
 '{community,drop-in,free,indoor,quiet}', true, true, false, 'Boyle Street Community Services', 'Drop-in Centre'),
('YESS – Resource Navigation',
 'Support with housing, food, and wellbeing. Trauma-informed.',
 '{community,free,quiet,indoor,small-group}', true, true, false, 'YESS', 'Resource Centre'),
('The Family Centre – Walk-In Counselling',
 'Single-session, solution-focused counselling. Pay-what-you-can options.',
 '{mental-health,indoor,routine}', false, true, false, 'The Family Centre', 'Counselling'),
('City of Edmonton – Youth Recreation Drop-In',
 'Supervised sports and games. Good for routine and gentle activity.',
 '{sports,drop-in,community,free,indoor}', true, true, false, 'City of Edmonton', 'Recreation Centre'),
('CMHA Edmonton – Peer Support / Groups',
 'Peer-based mental health support groups (themes vary).',
 '{mental-health,community,quiet,indoor}', true, true, false, 'CMHA Edmonton', 'Community Space'),
('Bent Arrow – Cultural & Youth Programs',
 'Programs connecting Indigenous youth with culture and community.',
 '{community,indoor,creative,leadership}', true, true, false, 'Bent Arrow Traditional Healing Society', 'Program Site'),
('Edmonton Public Library – Teen Space',
 'Study, makerspace tools, and teen events. Calm indoor time.',
 '{indoor,free,quiet,learning}', true, true, false, 'Edmonton Public Library', 'Branch Teen Area'),
('Community Skate / Movement Hour',
 'Gentle outdoor movement. Low-pressure and friendly.',
 '{outdoor,free,gentle-activity}', true, false, true, 'Community Partners', 'Local Park'),
('Youth Maker & Tech Club',
 'Beginner-friendly coding, 3D printing, and creative tech with mentors.',
 '{tech,creative,learning,indoor}', true, true, false, 'Community Lab', 'Makerspace');
