-- Edmonton Youth Programs Seed Data
-- Real programs serving ages 13-25 with mood tags and wellness dimensions
-- Generated: November 2025

-- Delete existing test programs first (keep the real ones)
DELETE FROM programs WHERE title LIKE 'Test %';

-- Insert comprehensive Edmonton youth programs
INSERT INTO programs (
  title, 
  description, 
  organizer, 
  location_name, 
  address, 
  city, 
  postal_code, 
  lat, 
  lng,
  tags,
  wellness_dimensions,
  age_min,
  age_max,
  free,
  drop_in,
  contact_email,
  contact_phone,
  website,
  created_at,
  updated_at
) VALUES

-- MENTAL HEALTH & COUNSELING PROGRAMS --

(
  'Kickstand – Walk-In Mental Health Hub',
  'Free, safe mental health services for ages 11-25 at West Edmonton Mall. No referral needed - just walk in or book online. Services include mental health counseling, substance use support, peer support, Indigenous wellness, employment help, and primary care. Youth-designed space with over 20 service providers.',
  'Kickstand Edmonton (YMCA)',
  'West Edmonton Mall - Level 2',
  '8882 170 St NW (Level 2, next to The Brick)',
  'Edmonton',
  'T5T 4J2',
  53.5227,
  -113.6218,
  ARRAY['mental-health', 'drop-in', 'drop_in', 'free', 'indoor', 'counselling', 'counseling', 'support', 'Indigenous', 'community', 'low_barrier'],
  ARRAY['emotional', 'social', 'physical', 'occupational'],
  11,
  25,
  true,
  true,
  '[email protected]',
  '587-337-0125',
  'https://mykickstand.ca/communities/edmonton/',
  NOW(),
  NOW()
),

(
  'ACCESS Open Minds – Walk-In Counseling',
  'Free walk-in mental health and addiction counseling for youth 16-25. No appointment needed. Solution-focused sessions (45-60 min) with clinicians. Can return as needed or get referred to psychiatry, addiction services, employment support, or group programs. Open Mon-Fri 12-5pm (last walk-in 4pm).',
  'ACCESS Open Minds Edmonton',
  'Community Mental Health Clinic',
  'Contact for location details',
  'Edmonton',
  NULL,
  53.5461,
  -113.4938,
  ARRAY['mental-health', 'free', 'indoor', 'counselling', 'counseling', 'support', 'quiet', 'drop-in', 'drop_in', 'low_barrier'],
  ARRAY['emotional', 'social', 'intellectual'],
  16,
  25,
  true,
  true,
  NULL,
  '780-424-2424',
  'https://accessopenminds.ca/our_site/edmonton-ab-2/',
  NOW(),
  NOW()
),

(
  'Y Mind – Anxiety & Stress Management',
  'Free 7-week mental wellness program for teens and young adults experiencing anxiety and stress. Small groups (10-12 people) with trained facilitators using evidence-based techniques: Acceptance and Commitment Therapy, mindfulness, and self-compassion. Available in-person in Edmonton and virtually across Alberta. No diagnosis or YMCA membership required.',
  'YMCA of Northern Alberta',
  'Various YMCA Locations',
  'Contact for session location',
  'Edmonton',
  NULL,
  53.5461,
  -113.4938,
  ARRAY['mental-health', 'learning', 'indoor', 'community', 'mindfulness', 'support', 'free'],
  ARRAY['emotional', 'intellectual', 'social'],
  13,
  30,
  true,
  false,
  'ymind@ymcanab.ca',
  NULL,
  'https://ymcanab.ca/programs/learning-leadership-employment/youth-young-adults/y-mind',
  NOW(),
  NOW()
),

(
  'CASA Mental Health – Youth Services',
  'Comprehensive mental health treatment for children and youth ages 3-17. Services include outpatient therapy, day programs, school-based treatment, Indigenous-focused services, and residential care. First stop for most families dealing with mental health concerns. Requires referral via Recovery Alberta.',
  'CASA Mental Health',
  'CASA Centre',
  '10645-63 Ave NW',
  'Edmonton',
  'T6H 1N9',
  53.5145,
  -113.5098,
  ARRAY['mental-health', 'counselling', 'counseling', 'support', 'indoor', 'Indigenous', 'learning'],
  ARRAY['emotional', 'social', 'intellectual'],
  13,
  17,
  true,
  false,
  NULL,
  '780-342-4415',
  'https://casamentalhealth.org/',
  NOW(),
  NOW()
),

-- ARTS & CREATIVE PROGRAMS --

(
  'iHuman Youth Society – Arts Programs',
  'Arts-based programming for at-risk youth 12-24. Four creative disciplines: visual art (spray paint booth, exhibitions), music production (recording studio, instruments), fashion & beading (sewing machines, workshops), and performance art (theatre space). Includes free daily meals, mental health support, basic needs help, and wrap-around services. Must register first (free).',
  'iHuman Youth Society',
  'iHuman Studio',
  '9635 102A Ave NW',
  'Edmonton',
  'T5H 0H7',
  53.5569,
  -113.5008,
  ARRAY['arts', 'creative', 'indoor', 'mental-health', 'community', 'free', 'Indigenous'],
  ARRAY['emotional', 'creative', 'social', 'physical'],
  12,
  24,
  true,
  false,
  'info@ihuman.org',
  '780-421-8811',
  'https://ihuman.org/',
  NOW(),
  NOW()
),

(
  'Family Futures – Youth Connections Drop-In',
  'Free drop-in arts program for youth 11-24. Activities include painting, drawing, sculpting, crocheting, and mixed media. Safe, creative space to explore artistic expression and connect with peers. No registration required.',
  'Family Futures Resource Network',
  'Kickstand Location',
  '#101, 4341 Savaryn Drive SW',
  'Edmonton',
  'T6X 1V3',
  53.4425,
  -113.5842,
  ARRAY['arts', 'creative', 'drop-in', 'drop_in', 'free', 'indoor', 'community'],
  ARRAY['creative', 'social', 'emotional'],
  11,
  24,
  true,
  true,
  'info@familyfutures.ca',
  '780-413-4521',
  'https://familyfutures.ca/',
  NOW(),
  NOW()
),

-- INDIGENOUS PROGRAMS --

(
  'Bent Arrow – Coyote Pride Mentoring',
  'In-school mentoring program for Aboriginal youth in grades 7-9. Youth matched with Aboriginal mentors for cultural activities, traditional teachings, history education (including Residential Schools truth-telling), traditional games, and land-based learning with Elders. Emphasizes education importance and cultural values. Free program.',
  'Bent Arrow Traditional Healing Society',
  'Partner Schools',
  'Various school locations',
  'Edmonton',
  NULL,
  53.5461,
  -113.4938,
  ARRAY['Indigenous', 'learning', 'community', 'outdoor', 'mentorship', 'free'],
  ARRAY['spiritual', 'social', 'intellectual', 'cultural'],
  12,
  15,
  true,
  false,
  NULL,
  NULL,
  'https://bentarrow.ca/',
  NOW(),
  NOW()
),

-- COMMUNITY DROP-IN CENTERS --

(
  'Youth Rise – Northside Drop-In',
  'Free community youth center every Thursday 4-6pm at Alberta Avenue Community Centre. Sports in gym, video games, free food, mentorship, and safe space to connect with peers. No registration required - bring friends! 100% free.',
  'Youth Rise Edmonton',
  'Alberta Avenue Community Centre',
  '9210 118 Ave NW',
  'Edmonton',
  'T5G 0N2',
  53.5592,
  -113.5072,
  ARRAY['community', 'drop-in', 'drop_in', 'free', 'sports', 'indoor', 'social'],
  ARRAY['social', 'physical', 'emotional'],
  12,
  18,
  true,
  true,
  'hello@youthrise.ca',
  '587-404-6910',
  'https://www.youthrise.ca/',
  NOW(),
  NOW()
),

(
  'YESS – Emergency Shelter & Crisis Support',
  'Emergency shelter and crisis support for youth 15-24 experiencing homelessness. 24/7 access with 16 beds, food, clothing, showers, laundry. Daytime programs include primary medical care, mental health clinics, housing connections. 2SLGBTQIA+ friendly, harm reduction-minded, trauma-informed. Low-barrier access.',
  'Youth Empowerment and Support Services',
  'Youth Support Centre',
  '9310 82 Ave NW',
  'Edmonton',
  'T6C 1A4',
  53.5196,
  -113.5098,
  ARRAY['community', 'mental-health', 'indoor', 'crisis', 'free', 'housing', 'support', 'low_barrier'],
  ARRAY['physical', 'emotional', 'social', 'environmental'],
  15,
  24,
  true,
  true,
  NULL,
  NULL,
  'https://yess.org/',
  NOW(),
  NOW()
),

(
  'Boyle Street – Youth Unit Drop-In',
  'Walk-in support for street-involved and vulnerable youth 16-26. Open-door policy helping with immediate needs (food, clothing, first aid) and developing long-term action plans. Mon-Fri 8:30am-4pm (closed 12-1pm for lunch). No referral needed. Wheelchair accessible.',
  'Boyle Street Community Services',
  'Main Community Centre',
  '10527 96 Street NW',
  'Edmonton',
  'T5H 2H6',
  53.5532,
  -113.4968,
  ARRAY['community', 'drop-in', 'drop_in', 'free', 'indoor', 'crisis', 'support', 'low_barrier'],
  ARRAY['physical', 'social', 'emotional', 'environmental'],
  16,
  26,
  true,
  true,
  NULL,
  '587-336-5822',
  'https://www.boylestreet.org/',
  NOW(),
  NOW()
),

(
  'Youth Unlimited – Community Youth Centres',
  'Safe spaces with youth workers at multiple Edmonton locations. Free drop-in access to games (pool, sports), homework help, mentoring, and community. Barrier-free, judgment-free environment for teens. Always free.',
  'Youth Unlimited Edmonton',
  'Multiple Locations',
  'Various locations across Edmonton',
  'Edmonton',
  NULL,
  53.5461,
  -113.4938,
  ARRAY['community', 'drop-in', 'drop_in', 'free', 'indoor', 'social', 'mentorship'],
  ARRAY['social', 'intellectual', 'emotional'],
  13,
  19,
  true,
  true,
  NULL,
  NULL,
  'https://www.edmontonyouthunlimited.com/',
  NOW(),
  NOW()
),

-- RECREATION & SPORTS PROGRAMS --

(
  'City of Edmonton – Commonwealth Youth Programs',
  'Free youth programs at Commonwealth Recreation Centre, Mon-Fri 3:30-5:45pm. Programs include Youth Connections, Gym ROCKS, Brave Space, and Wolves Hockey. Sports, cultural, social, and academic activities for ages 8-17. No registration required for drop-in programs.',
  'City of Edmonton Recreation',
  'Commonwealth Recreation Centre',
  '11000 Stadium Rd NW',
  'Edmonton',
  'T5H 4E2',
  53.5597,
  -113.4760,
  ARRAY['sports', 'community', 'drop-in', 'drop_in', 'free', 'indoor', 'active', 'learning'],
  ARRAY['physical', 'social', 'intellectual'],
  8,
  17,
  true,
  true,
  NULL,
  '311',
  'https://www.edmonton.ca/programs_services/for_children_kids_youth/youth-programs',
  NOW(),
  NOW()
),

(
  'City of Edmonton – Clareview Youth Programs',
  'Free youth programs at Clareview Recreation Centre, Mon-Fri 3:30-6pm. Youth Connections and Core Youth Centre offering sports, social activities, and safe community space. Ages 8-17. Drop-in welcome.',
  'City of Edmonton Recreation',
  'Clareview Recreation Centre',
  '3804 139 Ave NW',
  'Edmonton',
  'T5Y 1Y5',
  53.6119,
  -113.4251,
  ARRAY['sports', 'community', 'drop-in', 'drop_in', 'free', 'indoor', 'active'],
  ARRAY['physical', 'social', 'emotional'],
  8,
  17,
  true,
  true,
  NULL,
  '311',
  'https://www.edmonton.ca/programs_services/for_children_kids_youth/youth-programs',
  NOW(),
  NOW()
),

(
  'City of Edmonton – The Meadows Youth Programs',
  'Free youth programs at The Meadows Recreation Centre, Mon-Fri 3:30-6pm. Youth ROCKS, Jr. Chef cooking classes, and Chess 101. Mix of physical activity, life skills, and social connection. Ages 8-17.',
  'City of Edmonton Recreation',
  'The Meadows Community Recreation Centre',
  '2704 17 Street NW',
  'Edmonton',
  'T6T 0J9',
  53.4625,
  -113.4082,
  ARRAY['sports', 'community', 'drop-in', 'drop_in', 'free', 'indoor', 'learning', 'active'],
  ARRAY['physical', 'social', 'intellectual'],
  8,
  17,
  true,
  true,
  NULL,
  '311',
  'https://www.edmonton.ca/programs_services/for_children_kids_youth/youth-programs',
  NOW(),
  NOW()
),

(
  'City of Edmonton – Terwillegar Youth Zone',
  'Free youth programs at ACT (Arts & Cultural Centre Terwillegar), Mon-Fri 12:30-5:45pm. Programs include Youth Zone, Indigenous Creative Corner, Ball Forever sports, and STEM activities. Cultural, creative, and athletic programming. Ages 8-17.',
  'City of Edmonton Recreation',
  'ACT - Arts & Cultural Centre Terwillegar',
  '2051 Leger Rd NW',
  'Edmonton',
  'T6R 0R1',
  53.4625,
  -113.5842,
  ARRAY['arts', 'sports', 'community', 'drop-in', 'drop_in', 'free', 'indoor', 'Indigenous', 'learning', 'creative'],
  ARRAY['creative', 'physical', 'intellectual', 'cultural'],
  8,
  17,
  true,
  true,
  NULL,
  '311',
  'https://www.edmonton.ca/programs_services/for_children_kids_youth/youth-programs',
  NOW(),
  NOW()
),

-- TECHNOLOGY & LEARNING PROGRAMS --

(
  'Edmonton Public Library – Teen Spaces',
  'Free teen-only spaces at library branches across Edmonton. Safe, quiet places to study, use computers, read, do homework, or hang out. Free WiFi, books, audiobooks, e-resources, and programs. Open during library hours.',
  'Edmonton Public Library',
  'Multiple Library Branches',
  'Various locations citywide',
  'Edmonton',
  NULL,
  53.5461,
  -113.4938,
  ARRAY['indoor', 'free', 'quiet', 'learning', 'tech', 'community'],
  ARRAY['intellectual', 'social'],
  13,
  19,
  true,
  true,
  NULL,
  '780-496-7000',
  'https://epl.ca/',
  NOW(),
  NOW()
),

(
  'Youth Maker & Tech Club',
  'Hands-on technology and maker programs for youth. Learn coding, 3D printing, robotics, digital art, and more. Creative tech projects in supportive environment. Located in community makerspace with tools and mentorship.',
  'Community Makerspace',
  'Tech Hub Makerspace',
  'Various locations',
  'Edmonton',
  NULL,
  53.5461,
  -113.4938,
  ARRAY['tech', 'creative', 'learning', 'indoor', 'community', 'STEM'],
  ARRAY['intellectual', 'creative', 'social'],
  12,
  19,
  true,
  false,
  NULL,
  NULL,
  NULL,
  NOW(),
  NOW()
),

-- SPECIALIZED MENTAL HEALTH PROGRAMS --

(
  'Boyle Street – Youth Community Support Program (YCSP)',
  'Intensive community-based mental health program for youth 13-17 with mental health or addiction diagnoses who frequently use hospital services. Interdisciplinary team includes clinicians, occupational therapists, psychiatrists, and caseworkers. Requires referral from psychiatrist. Serves 20-25 youth.',
  'Boyle Street Community Services',
  'Community-Based Program',
  'Various locations',
  'Edmonton',
  NULL,
  53.5461,
  -113.4938,
  ARRAY['mental-health', 'counselling', 'counseling', 'support', 'community', 'intensive'],
  ARRAY['emotional', 'social', 'intellectual', 'occupational'],
  13,
  17,
  true,
  false,
  NULL,
  '780-613-8901',
  'https://www.boylestreet.org/ycsp',
  NOW(),
  NOW()
),

(
  'Northgate Centre – Child & Adolescent Walk-In',
  'Walk-in mental health and substance use clinic for children, youth, and their caregivers. Alberta Health Services clinic providing immediate access to mental health professionals. Parent/caregiver attendance encouraged. Contact for current hours.',
  'Alberta Health Services',
  'Northgate Centre',
  'Contact for address',
  'Edmonton',
  NULL,
  53.5969,
  -113.4938,
  ARRAY['mental-health', 'indoor', 'counselling', 'counseling', 'support', 'free', 'drop-in', 'drop_in', 'low_barrier'],
  ARRAY['emotional', 'social', 'intellectual'],
  13,
  18,
  true,
  true,
  NULL,
  '780-342-4415',
  'https://www.albertahealthservices.ca/',
  NOW(),
  NOW()
),

-- OUTDOOR & ACTIVE PROGRAMS --

(
  'Community Skate – Outdoor Movement',
  'Free outdoor skating and movement activities at local parks. Gentle physical activity in fresh air. Bring your own skates or join walking groups. Weather-dependent. Great for gentle exercise and community connection.',
  'Community Recreation',
  'Various Local Parks',
  'Outdoor locations citywide',
  'Edmonton',
  NULL,
  53.5461,
  -113.4938,
  ARRAY['outdoor', 'free', 'gentle-activity', 'sports', 'community'],
  ARRAY['physical', 'social', 'environmental'],
  13,
  25,
  true,
  true,
  NULL,
  NULL,
  NULL,
  NOW(),
  NOW()
),

(
  'City Recreation – Youth Wellness Fitness',
  'After-school youth pass gives 75% discount on recreation centre memberships for ages 8-17. Access all fitness centres, pools, gyms citywide on weekdays. Youth 12-15 must complete free "Youth in Action" fitness course first. Great for building healthy habits.',
  'City of Edmonton Recreation',
  'All Recreation Centres',
  'Citywide locations',
  'Edmonton',
  NULL,
  53.5461,
  -113.4938,
  ARRAY['sports', 'active', 'indoor', 'physical', 'wellness'],
  ARRAY['physical', 'emotional', 'social'],
  8,
  17,
  false,
  false,
  NULL,
  '311',
  'https://www.edmonton.ca/activities_parks_recreation/after-school-youth-pass',
  NOW(),
  NOW()
);

-- Update replit.md timestamp
COMMENT ON TABLE programs IS 'Last seeded with real Edmonton programs: November 10, 2025';
